name: t_store
description: "Ecommerce application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

#----------- PACKAGES ------------#

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  logger: ^2.5.0

  # Splash Screen Dependency
  flutter_native_splash: ^2.4.4
  # Onboarding Screen Dependency for dot indicator
  smooth_page_indicator: ^1.2.0+3


  connectivity_plus: ^6.1.2
  lottie: ^3.3.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0 # For Image Slider
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800